#!/bin/bash
# initializeCommand.sh
#
# Runs on the Codespaces HOST VM before containers start (before docker compose up).
# Generates two gitignored files:
#   - .devcontainer/.env          → N8N_ENCRYPTION_KEY + WEBHOOK_URL for n8n
#   - .devcontainer/searxng/settings.yml → SearXNG config with generated secret key
#
# IDEMPOTENT: existing files are never overwritten, so keys stay stable across
# codespace suspensions/resumes.
#
# KEY STABILITY on codespace RECREATION:
#   Set N8N_ENCRYPTION_KEY as a GitHub Codespaces Secret in your repo settings
#   (Settings → Secrets and variables → Codespaces).
#   When set, it is injected here as an env var and written to .env, ensuring
#   your n8n credentials remain readable even after deleting and recreating
#   the codespace.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
SETTINGS_TEMPLATE="${SCRIPT_DIR}/searxng/settings.yml.example"
SETTINGS_FILE="${SCRIPT_DIR}/searxng/settings.yml"

# ── Make all shell scripts executable ────────────────────────────────────────
# Required because the ollama entrypoint is called directly by Docker.
chmod +x "${SCRIPT_DIR}"/*.sh 2>/dev/null || true

# ── Generate .env ─────────────────────────────────────────────────────────────
if [ ! -f "${ENV_FILE}" ]; then
  echo "[init] Generating .devcontainer/.env ..."

  # Priority 1: GitHub Codespaces Secret (stable across recreations)
  # Priority 2: Random generation (lost if codespace is deleted)
  N8N_KEY="${N8N_ENCRYPTION_KEY:-$(openssl rand -hex 32)}"

  # Build the public WEBHOOK_URL for n8n.
  # In Codespaces, CODESPACE_NAME and GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN
  # are available as environment variables on the host VM.
  if [ -n "${CODESPACE_NAME:-}" ]; then
    DOMAIN="${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
    WEBHOOK_URL="https://${CODESPACE_NAME}-5678.${DOMAIN}/"
  else
    WEBHOOK_URL="http://localhost:5678/"
  fi

  cat > "${ENV_FILE}" <<EOF
# Generated by initializeCommand.sh — DO NOT COMMIT
# To make credentials persist across codespace recreation, set
# N8N_ENCRYPTION_KEY as a GitHub Codespaces Secret in your repo.

N8N_ENCRYPTION_KEY=${N8N_KEY}
WEBHOOK_URL=${WEBHOOK_URL}
EOF

  echo "[init] .env created (WEBHOOK_URL=${WEBHOOK_URL})"
else
  echo "[init] .env already exists — skipping generation."
fi

# ── Generate searxng/settings.yml ─────────────────────────────────────────────
if [ ! -f "${SETTINGS_FILE}" ]; then
  echo "[init] Generating .devcontainer/searxng/settings.yml ..."

  if [ ! -f "${SETTINGS_TEMPLATE}" ]; then
    echo "[init] ERROR: ${SETTINGS_TEMPLATE} not found. Cannot generate settings.yml." >&2
    exit 1
  fi

  # Generate a fresh 32-byte hex secret for SearXNG cookie signing.
  SRX_KEY=$(openssl rand -hex 32)

  # Replace the placeholder in the template and write the real file.
  sed "s/CHANGE_ME_GENERATED_BY_INIT/${SRX_KEY}/g" "${SETTINGS_TEMPLATE}" > "${SETTINGS_FILE}"

  echo "[init] searxng/settings.yml created."
else
  echo "[init] searxng/settings.yml already exists — skipping generation."
fi

echo "[init] Initialization complete."
